AddCSLuaFile()

-- i'd joke about there being pain involved in making this, but in reality i made a script to do this for me

local pt = {98,102}

sound.Add({name = "Weapon_30cal.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^30cal/30cal_shoot.wav"})
sound.Add({name = "Weapon_30cal.BoltBack", channel = 3, volume = 1, level = 75, pitch = 100, sound = "30cal/30cal_boltback.wav"})
sound.Add({name = "Weapon_30cal.BoltForward", channel = 3, volume = 1, level = 75, pitch = 100, sound = "30cal/30cal_boltforward.wav"})
sound.Add({name = "Weapon_30cal.BulletChain1", channel = 3, volume = 1, level = 75, pitch = 100, sound = "30cal/30cal_bulletchain1.wav"})
sound.Add({name = "Weapon_30cal.BulletChain2", channel = 3, volume = 1, level = 75, pitch = 100, sound = "30cal/30cal_bulletchain2.wav"})
sound.Add({name = "Weapon_30cal.CoverUp", channel = 3, volume = 1, level = 75, pitch = 100, sound = "30cal/30cal_coverup.wav"})
sound.Add({name = "Weapon_30cal.CoverDown", channel = 1, volume = 1, level = 75, pitch = 100, sound = "30cal/30cal_coverdown.wav"})
sound.Add({name = "Weapon_30cal.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_30cal.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "30cal/30cal_worldreload.wav"})

sound.Add({name = "Weapon_Bar.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^bar/bar_shoot.wav"})
sound.Add({name = "Weapon_Bar.BoltBack", channel = 3, volume = 1, level = 75, pitch = 100, sound = "bar/bar_boltback.wav"})
sound.Add({name = "Weapon_Bar.BoltForward", channel = 3, volume = 1, level = 75, pitch = 100, sound = "bar/bar_boltforward.wav"})
sound.Add({name = "Weapon_Bar.ClipIn1", channel = 3, volume = 1, level = 75, pitch = 100, sound = "bar/bar_clipin1.wav"})
sound.Add({name = "Weapon_Bar.ClipIn2", channel = 3, volume = 1, level = 75, pitch = 100, sound = "bar/bar_clipin2.wav"})
sound.Add({name = "Weapon_Bar.ClipOut", channel = 3, volume = 1, level = 75, pitch = 100, sound = "bar/bar_clipout.wav"})
sound.Add({name = "Weapon_Bar.SelectorSwitch", channel = 3, volume = 1, level = 75, pitch = 100, sound = "bar/bar_selectorswitch.wav"})
sound.Add({name = "Weapon_Bar.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_Bar.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "bar/bar_worldreload.wav"})

sound.Add({name = "Weapon_Bazooka.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^bazooka/rocket1.wav"})
sound.Add({name = "Weapon_Bazooka.ClipIn", channel = 3, volume = 1, level = 75, pitch = 100, sound = "bazooka/rocket_clipin.wav"})
sound.Add({name = "Weapon_Bazooka.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_Bazooka.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "bazooka/rocket_worldreload.wav"})

sound.Add({name = "Weapon_Carbine.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^m1carbine/m1carbine_shoot.wav"})
sound.Add({name = "Weapon_Carbine.BoltBack", channel = 3, volume = 1, level = 75, pitch = 100, sound = "m1carbine/m1carbine_boltback.wav"})
sound.Add({name = "Weapon_Carbine.BoltForward", channel = 3, volume = 1, level = 75, pitch = 100, sound = "m1carbine/m1carbine_boltforward.wav"})
sound.Add({name = "Weapon_Carbine.ClipIn1", channel = 3, volume = 1, level = 75, pitch = 100, sound = "m1carbine/m1carbine_clipin1.wav"})
sound.Add({name = "Weapon_Carbine.ClipIn2", channel = 3, volume = 1, level = 75, pitch = 100, sound = "m1carbine/m1carbine_clipin2.wav"})
sound.Add({name = "Weapon_Carbine.ClipOut", channel = 3, volume = 1, level = 75, pitch = 100, sound = "m1carbine/m1carbine_clipout.wav"})
sound.Add({name = "Weapon_Carbine.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_Carbine.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "m1carbine/m1carbine_worldreload.wav"})

sound.Add({name = "Weapon_Colt.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^colt/colt_shoot.wav"})
sound.Add({name = "Weapon_Colt.ClipOut", channel = 3, volume = 1, level = 75, pitch = 100, sound = "colt/colt_clipout.wav"})
sound.Add({name = "Weapon_Colt.ClipIn", channel = 3, volume = 1, level = 75, pitch = 100, sound = "colt/colt_clipin.wav"})
sound.Add({name = "Weapon_Colt.BoltBack", channel = 3, volume = 1, level = 75, pitch = 100, sound = "colt/colt_boltback.wav"})
sound.Add({name = "Weapon_Colt.BoltForward", channel = 3, volume = 1, level = 75, pitch = 100, sound = "colt/colt_boltforward.wav"})
sound.Add({name = "Weapon_Colt.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_pistol.wav"})
sound.Add({name = "Weapon_Colt.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "colt/colt_worldreload.wav"})

sound.Add({name = "Weapon_C96.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^c96/c96_shoot.wav"})
sound.Add({name = "Weapon_C96.ClipOut", channel = 3, volume = 1, level = 75, pitch = 100, sound = "c96/c96_clipout.wav"})
sound.Add({name = "Weapon_C96.ClipIn1", channel = 3, volume = 1, level = 75, pitch = 100, sound = "c96/c96_clipin1.wav"})
sound.Add({name = "Weapon_C96.ClipIn2", channel = 3, volume = 1, level = 75, pitch = 100, sound = "c96/c96_clipin2.wav"})
sound.Add({name = "Weapon_C96.BoltBack", channel = 3, volume = 1, level = 75, pitch = 100, sound = "c96/c96_boltback.wav"})
sound.Add({name = "Weapon_C96.BoltForward", channel = 3, volume = 1, level = 75, pitch = 100, sound = "c96/c96_boltforward.wav"})
sound.Add({name = "Weapon_C96.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_pistol.wav"})
sound.Add({name = "Weapon_C96.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "c96/c96_worldreload.wav"})

sound.Add({name = "Weapon_Garand.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^garand/garand_shoot.wav"})
sound.Add({name = "Weapon_Garand.ClipIn1", channel = 3, volume = 1, level = 75, pitch = 100, sound = "garand/garand_clipin1.wav"})
sound.Add({name = "Weapon_Garand.ClipIn2", channel = 3, volume = 1, level = 75, pitch = 100, sound = "garand/garand_clipin2.wav"})
sound.Add({name = "Weapon_Garand.ClipDing", channel = 6, volume = 1, level = 75, pitch = 100, sound = "garand/garand_clipding.wav"})
sound.Add({name = "Weapon_Garand.BoltForward", channel = 3, volume = 1, level = 75, pitch = 100, sound = "garand/garand_boltforward.wav"})
sound.Add({name = "Weapon_Garand.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_Garand.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "garand/garand_worldreload.wav"})

sound.Add({name = "Weapon_Kar.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^k98/k98_shoot.wav"})
sound.Add({name = "Weapon_KarScoped.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^k98/k98scoped_shoot.wav"})
sound.Add({name = "Weapon_K98.BoltBack1", channel = 3, volume = 1, level = 75, pitch = 100, sound = "k98/k98_boltback1.wav"})
sound.Add({name = "Weapon_K98.BoltBack2", channel = 3, volume = 1, level = 75, pitch = 100, sound = "k98/k98_boltback2.wav"})
sound.Add({name = "Weapon_K98.BoltForward1", channel = 3, volume = 1, level = 75, pitch = 100, sound = "k98/k98_boltforward1.wav"})
sound.Add({name = "Weapon_K98.BoltForward2", channel = 3, volume = 1, level = 75, pitch = 100, sound = "k98/k98_boltforward2.wav"})
sound.Add({name = "Weapon_K98.ClipIn", channel = 3, volume = 1, level = 75, pitch = 100, sound = "k98/k98_clipin.wav"})
sound.Add({name = "Weapon_K98.ClipIn2", channel = 3, volume = 0.5, level = 75, pitch = 100, sound = "k98/k98_clipin2.wav"})
sound.Add({name = "Weapon_K98.ClipOut", channel = 6, volume = 1, level = 75, pitch = 100, sound = "k98/k98_clipout.wav"})
sound.Add({name = "Weapon_K98.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_K98.SinglShotReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "k98/k98_singleshotreload.wav"})
sound.Add({name = "Weapon_K98.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "k98/k98_worldreload.wav"})

sound.Add({name = "Weapon_Luger.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^p38/p38_shoot.wav"})
sound.Add({name = "Weapon_Luger.ClipIn", channel = 3, volume = 1, level = 75, pitch = 100, sound = "p38/p38_clipin.wav"})
sound.Add({name = "Weapon_Luger.ClipOut", channel = 3, volume = 1, level = 75, pitch = 100, sound = "p38/p38_clipout.wav"})
sound.Add({name = "Weapon_Luger.BoltBack", channel = 3, volume = 1, level = 75, pitch = 100, sound = "p38/p38_boltback.wav"})
sound.Add({name = "Weapon_Luger.BoltForward", channel = 3, volume = 1, level = 75, pitch = 100, sound = "p38/p38_boltforward.wav"})
sound.Add({name = "Weapon_Luger.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_pistol.wav"})
sound.Add({name = "Weapon_Luger.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "p38/p38_worldreload.wav"})

sound.Add({name = "Weapon_Mg42.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^mg42/mg42_shoot.wav"})
sound.Add({name = "Weapon_Mg42.OverHeat", channel = 6, volume = 1, level = 75, pitch = 100, sound = "mg42/mg42_overheat.wav"})
sound.Add({name = "Weapon_Mg42.CoverUp", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mg42/mg42_coverup.wav"})
sound.Add({name = "Weapon_Mg42.CoverDown", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mg42/mg42_coverdown.wav"})
sound.Add({name = "Weapon_Mg42.BulletChain1", channel = 6, volume = 1, level = 75, pitch = 100, sound = "mg42/mg42_bulletchain1.wav"})
sound.Add({name = "Weapon_Mg42.BulletChain2", channel = 6, volume = 1, level = 75, pitch = 100, sound = "mg42/mg42_bulletchain2.wav"})
sound.Add({name = "Weapon_Mg42.BoltBack", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mg42/mg42_boltback.wav"})
sound.Add({name = "Weapon_Mg42.BoltForward", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mg42/mg42_boltforward.wav"})
sound.Add({name = "Weapon_Mg42.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_Mg42.DeployBipod", channel = 1, volume = 1, level = 75, pitch = 100, sound = "mg42/mg42_deploybipod.wav"})
sound.Add({name = "Weapon_Mg42.RaiseBipod", channel = 1, volume = 1, level = 75, pitch = 100, sound = "mg42/mg42_raisebipod.wav"})
sound.Add({name = "Weapon_Mg42.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "mg42/mg42_worldreload.wav"})

sound.Add({name = "Weapon_Mp40.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^mp40/mp40_shoot.wav"})
sound.Add({name = "Weapon_Mp40.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_Mp40.BoltBack", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mp40/mp40_boltback.wav"})
sound.Add({name = "Weapon_Mp40.ClipIn", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mp40/mp40_clipin.wav"})
sound.Add({name = "Weapon_Mp40.ClipOut", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mp40/mp40_clipout.wav"})
sound.Add({name = "Weapon_Mp40.BoltForward", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mp40/mp40_boltforward.wav"})
sound.Add({name = "Weapon_Mp40.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "mp40/mp40_worldreload.wav"})

sound.Add({name = "Weapon_Mp44.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^mp44/mp44_shoot.wav"})
sound.Add({name = "Weapon_Mp44.BoltBack", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mp44/mp44_boltback.wav"})
sound.Add({name = "Weapon_Mp44.BoltForward", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mp44/mp44_boltforward.wav"})
sound.Add({name = "Weapon_Mp44.ClipIn1", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mp44/mp44_clipin1.wav"})
sound.Add({name = "Weapon_Mp44.ClipIn2", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mp44/mp44_clipin2.wav"})
sound.Add({name = "Weapon_Mp44.ClipOut", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mp44/mp44_clipout.wav"})
sound.Add({name = "Weapon_Mp44.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_Mp44.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "mp44/mp44_worldreload.wav"})
sound.Add({name = "Weapon_Mp44.SelectorSwitch", channel = 3, volume = 1, level = 75, pitch = 100, sound = "mp44/mp44_selectorswitch.wav"})

sound.Add({name = "Weapon_Panzerschreck.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^bazooka/rocket1.wav"})
sound.Add({name = "Weapon_Panzerschreck.ClipIn", channel = 3, volume = 1, level = 75, pitch = 100, sound = "bazooka/rocket_clipin.wav"})
sound.Add({name = "Weapon_Panzerschreck.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_Panzerschreck.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "bazooka/rocket_worldreload.wav"})

sound.Add({name = "Weapon_Springfield.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^springfield/spring_shoot.wav"})
sound.Add({name = "Weapon_Springfield.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_Springfield.SinglShotReload", channel = 3, volume = 0.76953125, level = 75, pitch = 0, sound = "k98/k98_singleshotreload.wav"})
sound.Add({name = "Weapon_Springfield.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "k98/k98_worldreload.wav"})

sound.Add({name = "Weapon_Thompson.Shoot", channel = 1, volume = 1, level = 150, pitch = pt, sound = "^thompson/thompson_shoot.wav"})
sound.Add({name = "Weapon_Thompson.ClipIn", channel = 3, volume = 1, level = 75, pitch = 100, sound = "thompson/thompson_clipin.wav"})
sound.Add({name = "Weapon_Thompson.ClipOut", channel = 3, volume = 1, level = 75, pitch = 100, sound = "thompson/thompson_clipout.wav"})
sound.Add({name = "Weapon_Thompson.BoltBack", channel = 3, volume = 1, level = 75, pitch = 100, sound = "thompson/thompson_boltback.wav"})
sound.Add({name = "Weapon_Thompson.BoltForward", channel = 3, volume = 1, level = 75, pitch = 100, sound = "thompson/thompson_boltforward.wav"})
sound.Add({name = "Weapon_Thompson.Draw", channel = 4, volume = 1, level = 75, pitch = 100, sound = "general/draw_rifle.wav"})
sound.Add({name = "Weapon_Thompson.WorldReload", channel = 3, volume = 0.76953125, level = 65, pitch = 100, sound = "thompson/thompson_worldreload.wav"})

print("ACF-3 SWEPS SOUND")